name: Update Svoboda file

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download file
        run: curl -o Svoboda.txt https://raw.githubusercontent.com/Temnuk/naabuzil/main/Svoboda

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Svoboda.txt
          git commit -m "Auto update" || echo "No changes"
          git push
